PREFIX ex: <http://example.org/planets/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?subject
WHERE {
  ?subject ex:satellite ?object.
  ?object ex:name ?name.
  FILTER langMATCHES(LANG(?name),"en")
}